name: create kops cluster

on:
    workflow_dispatch:
      inputs:
        cluster_name:
          description: 'name ofcluster'
          required: true
          default: 'warning'
          type: choice
          options:
          - choose
          - kubeclusterapp.com
          - clusterplay.com
          - klusterapp.com
        kops_state_store:
          description: 'Pick which bucket to use'
          required: true
          type: choice
          options:
            - choose
            - s3://kops-state-bk2
            - sk-store
            - ck-store
        environment:
          description: 'Environment to run tests against'
          type: choice
          required: true
          options:
            - choose
            - dev
            - stg
            - prd
        region:
          description: 'Region to use'
          type: choice
          required: true
          options:
            - choose
            - us-east-1
            - us-east-1
            - us-west-1
        zones:
          description: 'zones'
          type: choice
          required: true
          options:
            - choose
            - us-east-1a,us-east-1b,us-east-1c
            - us-east-1b
            - us-east-1c
        control_plane_size:
          description: 'control plane size'
          type: choice
          required: true
          options:
            - choose
            - t2.micro
            - t3.micro
            - t3.nano
        node_size:
          description: 'node size'
          type: choice
          required: true
          options:
            - choose
            - t2.micro
            - t3.micro
            - t3.nano
        count:
          description: "node count"
          type: choice
          required: true
          options:
            - choose
            - 3
            - 6
            - 9
        
        
jobs:
  cluster-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: installing latest version of kops
        run: |
              curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
              chmod +x kops-linux-amd64
              sudo mv kops-linux-amd64 /usr/local/bin/kops

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}


      - name: creating the cluster
        run: |
              export ZONES="${{ inputs.zones }}"
              kops create cluster ${{ inputs.cluster_name }} \
              --state=${{ inputs.kops_state_store }} \
              --node-count ${{ inputs.count }} \
              --zones $ZONES \
              --node-size ${{ inputs.node_size}} \
              --control-plane-size ${{ inputs.control_plane_size }} \
              --control-plane-zones ${{ inputs.zones }} \
              --networking cilium \
              --topology private \
              --bastion="true" \
              --yes

      - name: Setup Kops
        uses: hiberbee/github-action-kops@latest
        with:
          command: validate cluster
          cluster-name: ${{ inputs.cluster_name }}
          state-store: ${{ inputs.kops_state_store}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.region }}  